export const availableTags : string[] = [
  "react",
  "javaScript",
  "web development",
  "cricket",
  "netflix",
  "sports",
  "webseries",
  "fictional",
  "entertainment",
  "analytics",
  "education",
  "technology",
  "learning",
  "architecture",
  "scalability",
  "world cup",
  "online learning",
  "study tips",
  "Nnode.js",
  "python",
  "ai/ml",
  "design",
  "business",
  "health",
]